# CalLite Output Extraction

## Source Code
```{r sourceCode}
source(file.path('..','src','func_callite_post.R'))
```

## Load DSS Rip Package (only runs in 32bit R)
```{r message=FALSE, warning=FALSE}
options(dss_location="C:\\Program Files (x86)\\HEC\\HEC-DSSVue 2.0.1")
options(dss_jre_location="C:\\Program Files (x86)\\HEC\\HEC-DSSVue 2.0.1\\java")
Sys.setenv(JAVA_HOME="C:\\Program Files (x86)\\HEC\\HEC-DSSVue 2.0.1\\java")
library(dssrip)
```

## Declare SV Variables
```{r}
#  collect certain variables from the sv dss
res <-  dbSendQuery(con, paste(
  "SELECT * FROM calliteSV_var WHERE id IN (",
  paste(shQuote(c(487:525 #res inflows
                  # 45:62 #AD terms
                  )), collapse=", "),");"))
svVar <- dbFetch(res)
dbClearResult(res)
```

## Declare DV Variables
```{r message=FALSE, warning=FALSE}
res <-  dbSendQuery(con, paste(
  "SELECT * FROM calliteDV_var WHERE id IN (",
  paste(shQuote(c(
                  1205, # C_YoloBP
                  981, # C_SacDXC
                  720, # C_Hood,
                  977, # C_SacAm
                  2596, # I_Hood
                  2080, # D_Hood
                  675, # C_DXC
                  891, # C_NBA
                  985, # C_SacND
                  2586, # I_BrananIS
                  1999, # D_BrananIS
                  2600, # I_MarchCr
                  2614, # I_SacSJR
                  2191, # D_SacSJR
                  1948, # D_Antioch
                  986, # C_SacRV
                  1082, # C_SJRVI
                  659, # C_DELTA
                  993, # C_SACSJR
                  2043, # D_DELTAREQD
                  2007, # D_CCWD
                  2589, # I_ConeyIs
                  2024, # D_ConeyIs
                  2057, # D_ExpTD
                  1072, # C_SJRVer
                  916, # C_OldRiver
                  1046, # C_SJROldR
                  31, # AD_SJRCalALL
                  2623, # I_Stockton
                  2235, # D_Stockton
                  2624, # I_Terminous
                  2238, # D_Terminous
                  2603, # I_MedfordIS
                  2140, # D_MedfordIS
                  25, # AD_Mokelumne
                  2731, # NET DELTA DICU
                  1929, # DO_REQ
                  662, #C_Delta_ANN
                  540, #CO_MRDO
                  2341, #EM_MRDO
                  2640, #JP_MRDO
                  3016:3018, # RS_MRDO 1,2 and 3
                  671, # C_DELTA WHLCV
                  672, # C_DELTA WHLJP
                  665, # C_DELTA CVP
                  668, # C_DELTA SWP
                  917, # OMR
                  250, # C408 LBOUND
                  2087, # D_JONES
                  2106, # D_JONES_TD
                  2094, # D_JONES_CVP_TD
                  2090, # D_JONES_CVP
                  1950, # D_BANKS
                  1988, # D_BANKS_TD
                  1987, # D_BANKS_SWP_TD
                  1981, # D_BANKS_SWP
                  1969, # D_BANKS_CVP_TD
                  2358, # EXPORTACTUALTD
                  217, # BANKS ALLOW
                  2630, # JONES ALLOW
                  2631, # JONES MIN HS
                  2327, # EI EXP CTRL
                  189, # APRMAYEXPCTRL
                  2741, # NMFS_MAXECPCCDV
                  2742, # NMFS_MAXEXP
                  2475, # FWS_MAXEXP
                  2360, # EXPORT DEC RPA
                  2574, # INFFORX2NOV_DV
                  4037, # X2VERNMIN_REQDV
                  4040, # X2_PRV
                  185, # AN_EC_MONTH__SALINITY
                  353, # CH_EC_MONTH__SALINITY
                  354, # CI_EC_MONTH__SALINITY
                  473, # CO_EC_MONTH__SALINITY
                  474, # CO_EC_STD__SALINITY
                  628, # CV_EC_MONTH__SALINITY
                  2276, # EC_587_FINAL__SALINITY-EC
                  2279, # EC_589_FINAL__SALINITY-EC
                  2282, # EC_595_FINAL__SALINITY-EC
                  2285, # EC_605_FINAL__SALINITY-EC
                  2286, # EC_607_FINAL__SALINITY-EC
                  2289, # EC_608_FINAL__SALINITY-EC
                  2292, # EC_611_FINAL__SALINITY-EC
                  2295, # EC_614_FINAL__SALINITY-EC
                  2298, # EC_620_FINAL__SALINITY-EC
                  2301, # EC_637_FINAL__SALINITY-EC
                  2306, # EC_MERCED2_FINAL__SALINITY-EC
                  2309, # EC_SJRMAZE_FINAL__SALINITY-EC
                  2312, # EC_SJRMPBYP_FINAL__SALINITY-EC
                  2315, # EC_SJRSAND_FINAL__SALINITY-EC
                  2318, # EC_SJRTUOL_FINAL__SALINITY-EC
                  2321, # EC_STANRIPN_FINAL__SALINITY-EC
                  2324, # EC_TUOL_FINAL__SALINITY-EC
                  2337, # EM_EC_MONTH__SALINITY
                  2338, # EM_EC_STD__SALINITY
                  2636, # JP_EC_MONTH__SALINITY
                  2637, # JP_EC_STD__SALINITY
                  2670, # LV_EC_MONTH__SALINITY
                  2725, # MR_EC_MONTH__SALINITY
                  3008, # RS_CL_MONTH__SALINITY
                  3009, # RS_CL_STD__SALINITY
                  3010, # RS_EC_MONTH__SALINITY
                  3011, # RS_EC_STD__SALINITY
                  3012, # RS_ESTCL_NODXCDV__SALINITY
                  3001, # RSESTCLNODXCMEDV__SALINITY
                  4015, # VERNWQFINAL__SALINITY-EC
                  4016, # VERNWQNONPULSEDV__SALINITY-EC
                  4017, # VERNWQPULSEDV__SALINITY-EC
                  4018, # VI_EC_MONTH__SALINITY
                  1913, # DI_CVP
                  1914, # DI_SWP
                  1924, # DLT_IDX_CVP
                  1925, # DLT_IDX_SWP
                  621, # CVP TOTAL DEL
                  1790, # CVP_PAG_S DEL
                  3575:3717, # SWP Deliveries
                  3141:3150, # ShortAD
                  3157, # SHORT_C_MERCED1
                  3251, # SHORT_D_HST
                  2720, # MRDO ANN Relax
                  2362, # EXP ANN Relax
                  3156, # SHORT CVP TOTAL
                  3266:3268, # SHORT SWP N, S and TOTAL
                  3269:3272, # SIO STORAGE
                  3273:3276, # SJR Restoration
                  3572, # SWPRULECV
                  3718, # ESTMN
                  3725, # FOLSM
                  3742, # HNSLY
                  3749, # MCLRE
                  3757, # MELON
                  3763, # MLRTN
                  3773, # NHGAN
                  3781, # OROVL
                  3801, # PEDRO
                  3807, # SHSTA
                  3830, # SLCVP
                  3843, # SLSWP
                  3856, # TRNTY
                  3871, # WKYTN
                  2476:2484, # SPILLS
                  2435, # FOL Forecast
                  2766, # ORO Forecast
                  3140, # SHA Forecast
                  4033:4036 # WSI-DI
                  )), collapse=", "),");"))
dvVar <- dbFetch(res)
dbClearResult(res)
```


```{r message=FALSE, warning=FALSE}
varType <- 'DV'
simName <- paste0('sim_callite',varType,'_',runName)
dbExecute(con,paste("DROP TABLE IF EXISTS",simName))

# un-comment if not running SD perutbations (don't forget bracket at end of loop):
# simName <- paste0('sim_callite',varType,'_','pSacSD_TmonoNoAdap')
# dbExecute(con,paste("DROP TABLE IF EXISTS",simName))
# for (sd in c(1:10)){
#   sdChangeVal = sdChangeList[[sd]]; sdChangeName = names(sdChangeList)[sd]
#   runName <- paste0("pSac_",sdChangeName,"SD_TmonoNoAdap")
#   calLiteInputDir <- file.path(calliteRuns,runName)
#   print(calLiteInputDir)  
  
  for (p in c(2:7)) { # <- also change this if sd mode to `p in c(4)` 
    for (t in c(1:9)) {
      pChangeVal = pChangeList[[p]]; pChangeName = names(pChangeList)[p]
      tChangeVal = tChangeList[[t]]; tChangeName = names(tChangeList)[t]
      ptRunFolder <- paste0(pChangeName, "DP", tChangeName, "DT")
      print(ptRunFolder)
      collectDSSvar(varType, dvVar, con, simName, calLiteInputDir, ptRunFolder,
                    'DSS', calLiteRunCount, pChangeVal, tChangeVal, sdChangeVal=1) # <- also change this to sdChangeVal
    }
  }

# }
```

```{r}
# create annual summary table in database
createAnnualTable(con,runName,perturbY,perturbX)
```

```{r}
# Interpolation
dt_index <- 2
dp_index <- 3
water_years = c(900:1999)
for (chooseMetric in c(9)) {
  for (wy in water_years) {
    sql <- paste0('SELECT Water_Year, dt, ',
                  metrics$dbTableVar[chooseMetric], ' AS Metric',
                  ' FROM ', dbAnnualMetricsTbl,' WHERE dp=1.0 and Water_Year=',wy,
                  ' ORDER BY dt')
    res <- dbSendQuery(con,sql)
    dt_data <- dbFetch(res, n=-1)
    
    sql <- paste0('SELECT Water_Year, dp, ',
                  metrics$dbTableVar[chooseMetric], ' AS Metric',
                  ' FROM ', dbAnnualMetricsTbl,' WHERE dt=0.5 and Water_Year=',wy,
                  ' ORDER BY dp')
    res <- dbSendQuery(con,sql)
    dp_data <- dbFetch(res, n=-1)
    
    dt_data[dt_index,'Metric'] <- NA
    dp_data[dp_index,'Metric'] <- NA
    
    dt_data <- as.data.frame(na.approx(dt_data))
    dp_data <- as.data.frame(na.approx(dp_data))
    
    interp_val <- (dt_data[dt_index,'Metric'] + dp_data[dp_index,'Metric']) / 2
    
    sql <- paste0('UPDATE ',dbAnnualMetricsTbl, 
                  ' SET ', metrics$dbTableVar[chooseMetric],
                  '=',interp_val,
                  ' WHERE Water_Year=',wy,
                  ' and dp=',pChangeList[dp_index+1],' and dt=',tChangeList[dt_index])
    res <- dbSendQuery(con,sql)
  }
}

```

